

export const GET_USER_PROFILE  = 'GET_USER_PROFILE'
export const CREATE_USER_PROFILE = 'CREATE_USER_PROFILE'
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE' 
export const DELETE_USER_PROFILE = 'DELETE_USER_PROFILE'
